/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AwtrixAppInfo: typeof import('./components/AwtrixAppInfo.vue')['default']
    AwtrixDeviceInfo: typeof import('./components/AwtrixDeviceInfo.vue')['default']
    AwtrixGlobalStyle: typeof import('./components/AwtrixGlobalStyle.vue')['default']
    AwtrixNativeApp: typeof import('./components/AwtrixNativeApp.vue')['default']
    AwtrixTimeAppController: typeof import('./components/AwtrixTimeAppController.vue')['default']
    AwtrixTimeAppStyle: typeof import('./components/AwtrixTimeAppStyle.vue')['default']
    AwtrixTimeAppTimeMode: typeof import('./components/AwtrixTimeAppTimeMode.vue')['default']
    CAppSelection: typeof import('./components/CAppSelection.vue')['default']
    CAppSelectPlane: typeof import('./components/CAppSelectPlane.vue')['default']
    CAppTextColorSelection: typeof import('./components/CAppTextColorSelection.vue')['default']
    CBattery: typeof import('./components/CBattery.vue')['default']
    CColorSelection: typeof import('./components/CColorSelection.vue')['default']
    CGlobalTextColorSelection: typeof import('./components/CGlobalTextColorSelection.vue')['default']
    CLink: typeof import('./components/CLink.vue')['default']
    ColorPickerModal: typeof import('./components/modals/ColorPickerModal.vue')['default']
    CPullDown: typeof import('./components/CPullDown.vue')['default']
    CSingleInput: typeof import('./components/CSingleInput.vue')['default']
    CSingleNumberInput: typeof import('./components/CSingleNumberInput.vue')['default']
    CSlider: typeof import('./components/CSlider.vue')['default']
    CSwitch: typeof import('./components/CSwitch.vue')['default']
    CTimeModeItem: typeof import('./components/CTimeModeItem.vue')['default']
    CTimeModeSelection: typeof import('./components/CTimeModeSelection.vue')['default']
    CustomATag: typeof import('./components/CustomATag.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Link: typeof import('./components/Link.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scanner: typeof import('./components/Scanner.vue')['default']
    SwitchButton: typeof import('./components/SwitchButton.vue')['default']
    WifiIcon: typeof import('./components/WifiIcon.vue')['default']
  }
}
