/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/device-info': RouteRecordInfo<'/device-info', '/device-info', Record<never, never>, Record<never, never>>,
    '/device-setting': RouteRecordInfo<'/device-setting', '/device-setting', Record<never, never>, Record<never, never>>,
    '/reconnection/[refer]': RouteRecordInfo<'/reconnection/[refer]', '/reconnection/:refer', { refer: ParamValue<true> }, { refer: ParamValue<false> }>,
    '/scanner': RouteRecordInfo<'/scanner', '/scanner', Record<never, never>, Record<never, never>>,
    '/settings/time-app': RouteRecordInfo<'/settings/time-app', '/settings/time-app', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/device-info.vue': {
      routes: '/device-info'
      views: never
    }
    'src/pages/device-setting.vue': {
      routes: '/device-setting'
      views: never
    }
    'src/pages/reconnection/[refer].vue': {
      routes: '/reconnection/[refer]'
      views: never
    }
    'src/pages/scanner.vue': {
      routes: '/scanner'
      views: never
    }
    'src/pages/settings/time-app.vue': {
      routes: '/settings/time-app'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
